Add additional debug cases

diff --git a/.github/workflows/testing.yaml b/.github/workflows/testing.yaml
--- a/.github/workflows/testing.yaml
+++ b/.github/workflows/testing.yaml
@@ -68,14 +68,26 @@ jobs:
         run: |
           echo "'run-tests-1' with curlies: ${{ steps.run-tests-1.outputs.test_type }}"
 
-      - name: Gated by output of 'run-tests-0' and always()
+      - name: Gated by output of 'run-tests-0' and always
         if: always() && steps.run-tests-0.outputs.test_type == 'unit_test'
         shell: bash
         run: |
           echo "'run-tests-0' and always(): ${{ steps.run-tests-0.outputs.test_type }}"
 
-      - name: Gated by output of 'run-tests-1' no curlies
+      - name: Gated by output of 'run-tests-1' and always()
         if: always() && steps.run-tests-1.outputs.test_type == 'unit_test'
         shell: bash
         run: |
           echo "'run-tests-1' and always(): ${{ steps.run-tests-1.outputs.test_type }}"
+
+      - name: Gated by output of 'run-tests-0' and success() || failure()
+        if: (success() || failure()) && steps.run-tests-0.outputs.test_type == 'unit_test'
+        shell: bash
+        run: |
+          echo "'run-tests-0' and success() || failure(): ${{ steps.run-tests-0.outputs.test_type }}"
+
+      - name: Gated by output of 'run-tests-1' and success() || failure()
+        if: (success() || failure()) && steps.run-tests-1.outputs.test_type == 'unit_test'
+        shell: bash
+        run: |
+          echo "'run-tests-1' and success() || failure(): ${{ steps.run-tests-1.outputs.test_type }}"
